"""LightRAG HTTP client.

Auth is ONLY the X-API-Key header. Adding an Authorization: Bearer header makes
the server's OAuth2 scheme engage and reject with {"detail":"Invalid token"}.
"""
from __future__ import annotations

import httpx


class LightRAGClient:
    def __init__(self, base_url: str, api_key: str, timeout: float = 60.0):
        self._base = base_url.rstrip("/")
        self._headers = {"X-API-Key": api_key}
        self._timeout = timeout

    def get_graph(self, label: str = "*", max_nodes: int = 1000, max_depth: int = 6) -> dict:
        """Whole knowledge graph: {'nodes': [...], 'edges': [...]}."""
        r = httpx.get(
            f"{self._base}/graphs",
            params={"label": label, "max_nodes": max_nodes, "max_depth": max_depth},
            headers=self._headers, timeout=self._timeout,
        )
        r.raise_for_status()
        return r.json()

    def query_data(self, query: str, mode: str = "mix", top_k: int = 8) -> dict:
        """Retrieval context for a query: entities/relationships/keywords."""
        r = httpx.post(
            f"{self._base}/query/data",
            json={"query": query, "mode": mode, "only_need_context": True, "top_k": top_k},
            headers=self._headers, timeout=self._timeout,
        )
        r.raise_for_status()
        return r.json()

    def query_answer(self, query: str, mode: str = "mix") -> dict:
        """Full RAG answer generated by LightRAG: {'response': '...'}."""
        r = httpx.post(
            f"{self._base}/query",
            json={"query": query, "mode": mode},
            headers=self._headers, timeout=self._timeout,
        )
        r.raise_for_status()
        return r.json()

    def query_prompt(self, query: str, mode: str = "mix") -> dict:
        """The full prompt LightRAG assembles for the query — system role, goal,
        instructions and the entire KG+chunk context — WITHOUT generating an
        answer (only_need_prompt). Returned in {'response': '<prompt>'}."""
        r = httpx.post(
            f"{self._base}/query",
            json={"query": query, "mode": mode, "only_need_prompt": True},
            headers=self._headers, timeout=self._timeout,
        )
        r.raise_for_status()
        return r.json()
